name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Timer
        run: make -f timer.Makefile build
  
  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Run the Timer
        run: make -f timer.Makefile run
      - name: Go For a Minute
        run: make -f timer.Makefile run ARG1=0 ARG2=1 ARG3=0
  
  clean:
    runs-on: ubuntu-latest
    needs: run

    steps:
      - uses: actions/checkout@v4
      - name: Clean
        run: make -f timer.Makefile clean
